Board api documentation draft
hyecheol123/MakeBSSGreatAgain_API_Documentation pull request #13
Opened 2021-02-17 10:46 UTC by tmznwnel00

npm test passed
api files contents will be updated

2021-02-21 08:36 UTC, hyecheol123 requested changes
List of TODOs has been updated in the `openapi.yaml` file. please check those and update the code.

2021-02-22 08:37 UTC, hyecheol123 commented
We can merge at this point.
As of now, we finished basic article operations (Write, modify, delete, and read), and Like features.

We need to do search, report, and category features, but we are at a great point to take a short break and take a look back to see what we accomplished so far.

@tmznwnel00 If you are okay, let everyone to review the code and merge the code.

2021-02-22 08:40 UTC, hyecheol123 approved these changes

2021-02-22 09:14 UTC, wq0212 approved these changes

2021-02-22 10:01 UTC, merged